dirs:
  raw_data: raw_data
  processed_data: processed_data
  schemas: schemas
constants:
  ISO3: YEM
  crs: EPSG:2090
adm0:
  schema: admin0_affected_area_py.yml
  gadm:
    raw: gadm_adm0.zip
    processed: yem_admn_ad0_py_s0_gadm_pp.shp
    url: 'https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_YEM_gpkg.zip'
  cod:
    raw: cod_adm0.zip
    processed: yem_admn_ad0_py_s0_unocha_pp.shp
adm1:
  schema: admin1_affected_area_py.yml
  gadm:
    raw: gadm_adm1.zip
    processed: yem_admn_ad1_py_s0_gadm_pp.shp
    url: 'https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_YEM_gpkg.zip'
  cod:
    raw: cod_adm1.zip
    processed: yem_admn_ad1_py_s0_unocha_pp.shp
adm2:
  schema: admin2_affected_area_py.yml
  gadm:
    raw: gadm_adm2.zip
    processed: yem_admn_ad2_py_s0_gadm_pp.shp
    url: 'https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_YEM_gpkg.zip'  
  cod:
    raw: cod_adm2.zip
    processed: yem_admn_ad2_py_s0_unocha_pp.shp
adm3:
  schema: admin3_affected_area_py.yml
  gadm:
    raw: gadm_adm3.zip
    processed: yem_admn_ad3_py_s0_gadm_pp.shp
    url: 'https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_YEM_gpkg.zip'  
  cod:
    raw: cod_adm3.zip
    processed: yem_admn_ad3_py_s0_unocha_pp.shp
surrounding:
  schema: admin0_surrounding_countries_py.yml
  gadm:
    rawzip: gadm36_gpkg.zip
    raw: gadm36.gpkg
    processed: yem_admn_ad0_py_s0_gadm_pp_surrounding_countries.shp
    url: 'https://biogeo.ucdavis.edu/data/gadm3.6/gadm36_gpkg.zip'
geoboundaries:
  url: 'https://www.geoboundaries.org/gbRequest.html'
  raw: 'geobnd_'    # The Extract process will ammend the admX level and .zip 
  knownlevels: 3 
  downloadURL_api_key: 'downloadURL'
  boundaryType_api_key: 'boundaryType'
  adm0:
    raw: 'geobnd_adm0.zip'
    unzip: 'geobnd_adm0'
    processed: 'yem_admn_ad0_py_s0_geobnd_pp.shp'
  adm1:
    raw: 'geobnd_adm1.zip'
    processed: 'yem_admn_ad1_py_s0_geobnd_pp.shp'
  adm2:
    raw: 'geobnd_adm2.zip'
    processed: 'yem_admn_ad2_py_s0_geobnd_pp.shp'
roads:
  osm:
    raw: roads_osm.osm
    processed: yem_tran_rds_ln_s0_osm_pp.shp
    url: https://overpass-api.de/api/interpreter?data=(area[\"ISO3166-1\"=\"YE\"][\"admin_level\"=\"2\"];)->.a;(way[highway](area.a););(._;>;);out qt;
