dirs:
  raw_data: raw_data
  processed_data: processed_data
  schemas: schemas
constants:
  ISO3: YEM
  ISO2: YE
  crs: EPSG:2090
adm0:
  schema: admin0_affected_area_py.yml
  gadm:
    raw: gadm_adm0.zip
    processed: yem_admn_ad0_py_s0_gadm_pp.shp
    url: 'https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_YEM_gpkg.zip'
  cod:
    raw: cod_adm0.zip
    processed: yem_admn_ad0_py_s0_unocha_pp.shp
adm1:
  schema: admin1_affected_area_py.yml
  gadm:
    raw: gadm_adm1.zip
    processed: yem_admn_ad1_py_s1_gadm_pp.shp
    url: 'https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_YEM_gpkg.zip'
  cod:
    raw: cod_adm1.zip
    processed: yem_admn_ad1_py_s1_unocha_pp.shp
adm2:
  schema: admin2_affected_area_py.yml
  gadm:
    raw: gadm_adm2.zip
    processed: yem_admn_ad2_py_s2_gadm_pp.shp
    url: 'https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_YEM_gpkg.zip'  
  cod:
    raw: cod_adm2.zip
    processed: yem_admn_ad2_py_s2_unocha_pp.shp
adm3:
  schema: admin3_affected_area_py.yml
  gadm:
    raw: gadm_adm3.zip
    processed: yem_admn_ad3_py_s3_gadm_pp.shp
    url: 'https://biogeo.ucdavis.edu/data/gadm3.6/gpkg/gadm36_YEM_gpkg.zip'  
  cod:
    raw: cod_adm3.zip
    processed: yem_admn_ad3_py_s3_unocha_pp.shp
osm:
  url: 'http://overpass-api.de/api/interpreter?'
  lakes:
    osm_tags: 'osm_tags_lakes.yml'
    raw: osm_lakes.xml
    processed: yem_phys_lak_py_s1_osm_pp.shp
  rivers:
    osm_tags: 'osm_tags_rivers.yml'
    raw: osm_rivers.xml
    processed: yem_phys_riv_ln_s1_osm_pp.shp
  roads:
    osm_tags: 'osm_tags_roads.yml'
    raw: osm_roads.xml
    processed: yem_tran_rds_ln_s1_osm_pp.shp
  admin:
    osm_tags: 'osm_tags_admin.yml'
    raw: osm_admin.xml
  coastline:
    osm_tags: 'osm_tags_coast.yml'
    raw: osm_coast.xml
    processed: yem_phys_cst_ln_s1_osm_pp.shp
rivers:
  schema: rivers_affected_area_py.yml
  cod:
    raw: cod_rivers.zip
    processed: yem_phys_riv_ln_s1_unocha_pp.shp
seaports:
  schema: seaports_affected_area_py.yml
  cod:
    raw: cod_seaports.zip
    processed: yem_tran_por_pt_s1_unocha_pp.shp
surrounding:
  schema: admin0_surrounding_countries_py.yml
  gadm:
    rawzip: gadm36_gpkg.zip
    raw: gadm36.gpkg
    processed: yem_admn_ad0_py_s0_gadm_pp_surrounding_countries.shp
    url: 'https://biogeo.ucdavis.edu/data/gadm3.6/gadm36_gpkg.zip'
  geoboundaries:
    processed: yem_admn_ad0_py_s0_gedbnd_pp_surrounding_countries.shp
geoboundaries:
  # https://www.geoboundaries.org/api.html
  url: 'https://www.geoboundaries.org/gbRequest.html'
  typ: 'TYP=SSCGS'
  all: 'ISO=ALL&ADM=ADM0&TYP=SSCGS'
  isofield: 'shapeISO'
  subfolder: 'geoboundaries'
  raw: 'geobnd_'    # The Extract process will ammend the admX level and .zip 
  downloadURL_api_key: 'downloadURL'
  boundaryType_api_key: 'boundaryType'
  adm0:
    raw: 'geobnd_adm0.zip'
    unzip: 'geobnd_adm0'
    processed: 'yem_admn_ad0_py_s0_geobnd_pp.shp'
  adm1:
    raw: 'geobnd_adm1.zip'
    processed: 'yem_admn_ad1_py_s0_geobnd_pp.shp'
  adm2:
    raw: 'geobnd_adm2.zip'
    processed: 'yem_admn_ad2_py_s0_geobnd_pp.shp'
roads:
  schema: roads_affected_area_py.yml
  cod:
    raw: cod_roads.zip
    processed: yem_tran_rds_ln_s1_ocha_pp.shp
  osm:
    raw: roads_osm.osm
    processed: yem_tran_rds_ln_s1_osm_pp.shp
    url: https://overpass-api.de/api/interpreter?data=(area[\"ISO3166-1\"=\"YE\"][\"admin_level\"=\"2\"];)->.a;(way[highway](area.a););(._;>;);out qt;
airports:
    schema: airports_affected_area_py.yml
    ourairports:
      raw: our_airrports.shp
      processed: yem_tran_air_pt_s1_ourairports_pp.shp
    wfp:
      raw: wfp_airports.shp
      processed: yem_tran_air_pt_s1_wfp_pp